# Generated by Django 6.0 on 2025-12-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200, verbose_name='Nome Comum')),
                ('scientific_name', models.CharField(max_length=200, verbose_name='Nome Científico')),
                ('biomes', models.CharField(max_length=255, verbose_name='Biomas')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'ordering': ['common_name'],
            },
        ),
    ]
